server:
  port: 8080

eureka:
  client:
    serviceURL:
      defaultZone: http://localhost:8761/eureka
#  instance:
#    hostname: localhost

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: first-microservice
#          uri: http://localhost:8081/
          uri: lb://customer-service
          predicates:
            - Path=/first/**
        - id: second-microservice
          uri: lb://second
#          uri: http://localhost:8082/
          predicates:
            - Path=/message/**



management:
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: "*"