server:
  port: 8082

spring:
  application:
    name: second

eureka:
  client:
    serviceURL:
      defaultZone: http://localhost:8761/eureka
#  instance:
#    hostname: second

kafka:
  bootstrapAddress: localhost:29092
  consumer-config:
    topicName: test-topic
    groupId: test-group-id
  producer-config:
    topicName: test-topic
